let compteur = 0;
let a, b;
a = 0; b = "";
console.log('0 == "" -> ' + (a == b) + ' | 0 === "" -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = 0; b = "0";
console.log('0 == "0" -> ' + (a == b) + ' | 0 === "0" -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = 0; b = false;
console.log('0 == false -> ' + (a == b) + ' | 0 === false -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = ""; b = false;
console.log('"" == false -> ' + (a == b) + ' | "" === false -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = null; b = undefined;
console.log('null == undefined -> ' + (a == b) + ' | null === undefined -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = null; b = false;
console.log('null == false -> ' + (a == b) + ' | null === false -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = NaN; b = NaN;
console.log('NaN == NaN -> ' + (a == b) + ' | NaN === NaN -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = 1; b = "1";
console.log('1 == "1" -> ' + (a == b) + ' | 1 === "1" -> ' + (a === b));
if (a == b && a !== b) compteur++;
a = " \t\n "; b = 0;
console.log('" \\t\\n " == 0 -> ' + (a == b) + ' | " \\t\\n " === 0 -> ' + (a === b));
if (a == b && a !== b) compteur++;
console.log("----------");
console.log(compteur + " paire(s) où == et === donnent des résultats différents");